#!/usr/bin/env python3
"""Build dist/janus.lua: one file, from src/ in load order, with a version header.

    python3 tools/build.py            # writes dist/janus.lua and syntax-checks it if lua5.1 is found
"""
import os
import re
import shutil
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORDER = ['janus_core.lua', 'janus_units.lua', 'janus_presets.lua', 'janus_names.lua', 'janus_setup.lua']


def find_lua51():
    for cand in (os.environ.get('LUA51'), shutil.which('lua5.1'), shutil.which('lua51'), shutil.which('lua'),
                 os.path.expanduser('~/bin/lua5.1')):
        if cand and os.path.exists(cand):
            try:
                v = subprocess.run([cand, '-v'], capture_output=True, text=True)
                if '5.1' in (v.stdout + v.stderr):
                    return cand
            except OSError:
                pass
    return None


def main():
    parts = []
    version = 'unknown'
    for fn in ORDER:
        p = os.path.join(REPO, 'src', fn)
        src = open(p, encoding='utf-8').read()
        m = re.search(r'M\.VERSION\s*=\s*"([^"]+)"', src)
        if m:
            version = m.group(1)
        parts.append('-- ==================================================================== %s\n%s' % (fn, src.rstrip() + '\n'))
    header = ('-- Janus IADS %s - integrated air defence for DCS World, both coalitions, one file.\n'
              '-- https://github.com/Stonewalls-Claude/janus-iads   Licence: GPL-3.0\n'
              '-- GENERATED by tools/build.py from src/ - edit the sources, not this file.\n'
              '-- Install: Mission Editor trigger MISSION START -> DO SCRIPT FILE -> janus.lua. That is all.\n\n' % version)
    os.makedirs(os.path.join(REPO, 'dist'), exist_ok=True)
    out = os.path.join(REPO, 'dist', 'janus.lua')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header + '\n'.join(parts))
    size = os.path.getsize(out)
    print('wrote %s (%d bytes, version %s)' % (out, size, version))

    lua = find_lua51()
    if lua:
        r = subprocess.run([lua, '-e', 'assert(loadfile(%r))' % out], capture_output=True, text=True)
        if r.returncode != 0:
            print('SYNTAX ERROR:', r.stderr.strip())
            sys.exit(1)
        print('syntax OK (%s)' % lua)
    else:
        print('no Lua 5.1 interpreter found; syntax not checked here (dcs-check does it on the PC)')


if __name__ == '__main__':
    main()
